title: catch-dev
author: mariocatch
email: trust.dev42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software development blog

# social links
twitter_username: mario_catch # DO NOT include the @ character, or else the build will fail!
github_username:  mariocatch # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
